### PR TITLE
PR_issue_302

### PR DESCRIPTION
**Pull request by bscheltinga**
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/302

### CODE REVIEW

**Review by wbaccinelli — APPROVED** [review]
Perfect!

**Comment by nelealbers** [comment]
@bscheltinga I have in the meantime merged a new version of the database with different changes. So you might want to regenerate your version.

**Comment by bscheltinga** [comment]
> @bscheltinga I have in the meantime merged a new version of the database with different changes. So you might want to regenerate your version.

Ah yeah, that is required then...

**Comment by bscheltinga** [comment]
> @bscheltinga I have in the meantime merged a new version of the database with different changes. So you might want to regenerate your version.

I regenerate the version file. However, I did not see a difference between the two. So I think it was not needed in the end.

**Comment by nelealbers** [comment]
@bscheltinga The difference is in the name of the "down_revision" I think. Not sure how important.

**Review by wbaccinelli — APPROVED** [review]
Fine!

**Pull request merged**
